### ISSUE TITLE
Amélioration plugin office

### ISSUE THREAD

**Issue by gillesdubois** [PluginsOCSInventory-NG/officepack#1]
Améliorer le plugin Office afin :
1. D'avoir le nombre de poste par "office key"
2. D'avoir la liste des postes par "office key"
3. D'avoir le nom de licences par "office key"
4. Avoir le nom du poste associé à chaque licence ainsi que le tag
5. Dans la liste inventaire, sous le poste avoir la possibilité d'afficher la licence office.

**Comment by c-isi** [comment]
Eventuellement,
Avoir le nom du poste associé à chaque licence ainsi que le tag
Dans la liste inventaire, sous le poste avoir la possibilité d'afficher la licence office.

**Comment by gillesdubois** [comment]
Ajouté

**Comment by c-isi** [comment]
cool ^^

**Comment by ilogus** [comment]
Bonjour, possibilité d'afficher l'état de validité de la licence ?
Cordialement,
