### ISSUE TITLE
msofficekey.vbs does not list ALL keys in certain circumstances

### ISSUE THREAD

**Issue by ronator** [PluginsOCSInventory-NG/officepack#10]
It occurred to me, that when I have a windows client that has two different MS product installations (like Visio 2010 AND Office 2013) then this script will only detect one key (Visio in my case) and that's it, never reporting the other key. I assume the script is quiting to early. I can't really read vbs but I will try again but any help on this issue would be appreciated, because for now it is not collecting all available key data as if it assumes to detect only one "officepack" and not regarding the possibility that you could have two versions installed - or just one program from an older office version (like with Visio). Can someone confirm this issue?

**Comment by vdeville** [comment]
Hello @ronator 
Yes, VBS return only one.
Thank for your contribution

**Comment by gillesdubois** [comment]
Updated : 
https://github.com/PluginsOCSInventory-NG/officepack/releases/download/1.1/officepack.zip
