### ISSUE TITLE
Cant install plugin

### ISSUE THREAD

**Issue by hserras** [PluginsOCSInventory-NG/officepack#11]
Hi all,

When I put the officepack or other plugin in the correct download folder, it appears in the web GUI for installation. But when I hit the Install button, it goes to a blank page and it doesnt install.

I have a fresh installation of OCS 2.2 in ubuntu server 16.04

Thanks in advance

Regards
Hugo Serras

**Comment by ronator** [comment]
It could be, you are missing libzip in your system.

**Comment by hserras** [comment]
Thanks for the tip, ronator.

Going to try tomorrow when I get to work, and i'll give you the feedback.

**Comment by hserras** [comment]
Good morning, ronator,

Unfortunately, even after installing libzip4, which wasn't installed, I still can't get the plugins installed. The behavior is exactly the same. I click to install and the rest of the page stays blank.

I would appreciate any help, if possible.

Thanks in advance
Hugo Serras

**Comment by vdeville** [comment]
Hello @hserras ,
Your problem is not associate with officepack plugin.
Please review your installation and test fresh install with latest release of OCS Reports https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases
If you want more help you can go our IRC.
Regards
