### ISSUE TITLE
ERROR: officepack-master is an invalid plugin, check your sources. Installation aborted !

### ISSUE THREAD

**Issue by PaveLGIL** [PluginsOCSInventory-NG/officepack#12]
Hello!
I'm trying to install officepack plugin. But whet i try install i see this error "ERROR: officepack-master is an invalid plugin, check your sources. Installation aborted !
Maybe can you help me?
![screen shot 2016-08-02 at 3 44 49 pm](https://cloud.githubusercontent.com/assets/15833990/17328896/c127bb48-58c8-11e6-9f63-8d4171a559c1.png)
".

**Comment by vdeville** [comment]
Hello @PaveLGIL,
Can  you try with the latest release ? https://github.com/PluginsOCSInventory-NG/officepack/releases/download/1.0/officepack.zip
Thank,

**Comment by froloito** [comment]
Hello @OCSInventory-NG
I am doing the steps you mentioned above and successfully install the plugin. You can also see the section "Office License" in the software module, but I do not register the information of the office licenses.
Place the .vbs file in C: / Program Files (x86) / ocsinventory / plugins / but it does not report the information to me. Any suggestions
Thank you

**Comment by froloito1** [comment]
@MyTheValentinus 
please help me.
Hello
I am doing the steps you mentioned above and successfully install the plugin. You can also see the section "Office License" in the software module, but I do not register the information of the office licenses.
Place the .vbs file in C: / Program Files (x86) / ocsinventory / plugins / but it does not report the information to me. Any suggestions
Thank you
