### ISSUE TITLE
officeplugin not appear in ocs 

### ISSUE THREAD

**Issue by salamlz** [PluginsOCSInventory-NG/officepack#13]
good mornig plz
could help me 
I am copy and past the folder of download but its seems like this:

![plugin](https://cloud.githubusercontent.com/assets/21667869/18167708/7264e4aa-7028-11e6-8daf-446cf7d43170.JPG)

any help plz

**Comment by gillesdubois** [comment]
Hi,

You don't have to unzip the file.
Just take https://github.com/PluginsOCSInventory-NG/officepack/releases/download/1.0/officepack.zip and put it in the download folder.

Regards,
Gilles Dubois.

**Comment by salamlz** [comment]
yes my friend .. I am not unzip it .. I put in the download folder and he make this problem 
any plugin i put its make the same problems not only office. 
could you help plz. 

Regards

**Comment by vdeville** [comment]
Hello @salamlz ,
Your download folder is readable by apache ?

**Comment by salamlz** [comment]
hello 
what do you mean ? permission?

**Comment by salamlz** [comment]
yes yes .. plz see the pic here 
![apche](https://cloud.githubusercontent.com/assets/21667869/18176437/fc6eea9c-704b-11e6-9a3f-4d82573952ad.JPG)

**Comment by salamlz** [comment]
any plugin I get the same nothings as I showed in the first post the same pic
when I am remove the plugin form download folder the item plugin manger back normale like this now with no plugin  : 

![plugin normal](https://cloud.githubusercontent.com/assets/21667869/18176540/663ad0a8-704c-11e6-94c9-a6e6c9c868c2.JPG)

**Comment by vdeville** [comment]
Hello,
Can you take screenshot of 'ls -l' command in download folder ? Thank
