### ISSUE TITLE
cant install plugin

### ISSUE THREAD

**Issue by Scifire** [PluginsOCSInventory-NG/officepack#17]
Hello,
we use Server OCS 2.3 on Ubuntu 16.04, Agent 2.3.0.0. on Win 10.
First i tried to install the plugin with the old howto (cause i didn´t found this) but this didn´t worked.
Now i imported the plugin, but when i want to install it i get two red bars with: MySQL error: Installation aborted !

The plugin is not listed in database table plugins
i also removed all old things from teh plugin in:
 /etc/ocsinventory-server/plugins/
/etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/
/usr/share/ocsinventory-reports/ocsreports/plugins/computer_detail/

I didn´t get an error in the apache error.log also no error in the ocs log.

**Comment by gillesdubois** [comment]
Hi,

This bug has been fixed i will be pushing and creating a now release soon :) 
Thanks for your report.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

Can you clean these directories : 
/etc/ocsinventory-server/plugins/
/etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/
/usr/share/ocsinventory-reports/ocsreports/plugins/computer_detail/
/usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/

Remove all tables in the database which start by officepack_* and remove officepack entry in plugins table ( if there is one )

Here is the new version of the plugin with fixed database bug / support for 2016 and stats on licenses : 
https://github.com/PluginsOCSInventory-NG/officepack/releases/download/1.1/officepack.zip

Regards,
Gilles Dubois.

**Comment by Scifire** [comment]
Thanks for the fast fix unfortunately it isn´t working for me.
I have still one line with "MySQL error: Installation aborted !" (before there were two lines ;-))

With clean you mean delete the office plugin? Or do you want that i delete all files in these directories?

**Comment by gillesdubois** [comment]
Can you post your error.log plz ? 

I mean delete everything which refer to officepack plugin. 

Regards,
Gilles Dubois.

**Comment by Scifire** [comment]
Error Log from Apache? you´ll find below

```
ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable
[Mon Jan 09 07:25:02.312522 2017] [ssl:warn] [pid 2961] AH01906: ocs:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Jan 09 07:25:02.312751 2017] [mpm_prefork:notice] [pid 2961] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_perl/2.0.9 Perl/v5.22.1 configured -- resuming normal operations
[Mon Jan 09 07:25:02.312758 2017] [core:notice] [pid 2961] AH00094: Command line: '/usr/sbin/apache2'
[Mon Jan 09 09:36:46.157947 2017] [mpm_prefork:notice] [pid 2961] AH00169: caught SIGTERM, shutting down
ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable
[Mon Jan 09 09:36:47.397367 2017] [ssl:warn] [pid 12284] AH01906: ocs:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable
[Mon Jan 09 09:36:47.685566 2017] [ssl:warn] [pid 12285] AH01906: ocs:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Jan 09 09:36:47.691319 2017] [mpm_prefork:notice] [pid 12285] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_perl/2.0.9 Perl/v5.22.1 configured -- resuming normal operations
[Mon Jan 09 09:36:47.691345 2017] [core:notice] [pid 12285] AH00094: Command line: '/usr/sbin/apache2'

```
Error log from mysql is full of 
```
2017-01-09T08:09:40.523027Z 9078 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
2017-01-09T08:09:46.730703Z 9081 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
2017-01-09T08:09:48.603770Z 9086 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
2017-01-09T08:16:17.338707Z 9094 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
2017-01-09T08:16:19.969295Z 9101 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
2017-01-09T08:17:43.156817Z 9109 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
2017-01-09T08:18:46.627338Z 9114 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
2017-01-09T08:18:48.900005Z 9121 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
2017-01-09T08:18:54.486492Z 9132 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
2017-01-09T08:34:53.153041Z 9141 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
2017-01-09T08:35:03.206014Z 9146 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
2017-01-09T08:35:15.387907Z 9156 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)

```
But ocs work so far

**Comment by gillesdubois** [comment]
@scifire91 : I will try to install the plugin on a Ubuntu 16.04 machine, don't have any clues on what's wrong with this plugin.

Maybe something php7 don't like ...

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,
Your problrem has been fixed.
I made a minor release to fix this problem.
https://github.com/PluginsOCSInventory-NG/officepack/releases/download/1.1.1/officepack.zip

Thanks for very much for your help.
Regards,
Gilles Dubois.

**Comment by Scifire** [comment]
Thanks a lot. Plugin works fine :>

**Comment by elpardal** [comment]
@gillesdubois I downgraded to php5.6 before you discovered that the error was mysql 5.7 :/
