### ISSUE TITLE
ms_officepack.php query error

### ISSUE THREAD

**Issue by cygars** [PluginsOCSInventory-NG/officepack#2]
Greetings,

you have wrong syntax in file ms_officepack on line 38:
    $sql['SQL']  .= "FROM officepack WHERE 1";
should be
    $sql['SQL']  .= "FROM officepack WHERE install=1";

Also are you planning on adding all the features from previous officepack version for version 2.1?
Summary of licences was awesome feature which is missing here.

Best Regards.

**Comment by gillesdubois** [comment]
Hi,

Fixed in the new version : 
https://github.com/PluginsOCSInventory-NG/officepack/releases/download/1.1/officepack.zip

regards,
Gilles Dubois.
