### ISSUE TITLE
List of Office Key

### ISSUE THREAD

**Issue by Scifire** [PluginsOCSInventory-NG/officepack#20]
Hey,

i don´t know if the function is not available or if i only don´t know how to get it.
Is there a possibility to get a list of all office Keys? With the Windows license this is possible over search with various criteria but i didn´t get it for the office license.

OCS 2.3
officepack 1.1

**Comment by gillesdubois** [comment]
Hi @scifire91 ,

Actually there is no page to list all installed office licenses.
It might be a good idea to add it in the next version.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi @scifire91 ,

Licenses key can now be listed by versions :) 

Regards,
Gilles Dubois.
