### ISSUE TITLE
OCS don't send information

### ISSUE THREAD

**Issue by pepepedra** [PluginsOCSInventory-NG/officepack#23]
I've installed the plugin and I can see it at the plugins tab, but when I try to see the information about office license, no data is showed.
I've alrun the .vbs at the windows computer and it works.

Officepack: https://github.com/PluginsOCSInventory-NG/officepack/releases/download/1.1.1/officepack.zip
PHP Version :7.0.15
Web Server :Apache/2.4.18 (Ubuntu)
Database Server :Ubuntu) version 5.7.17-0ubuntu0.16.04.1
Version OCSReports: 2.3.1

Please, can someone tell me what I'm doing wrong?

Thanks in advance

**Comment by valentinastron** [comment]
The same problem here...

**Comment by ghost** [comment]
Same problem....how can we resolve this problem?

**Comment by hdadmin** [comment]
same problem here...

**Comment by Mant1kor** [comment]
Copy files from APACHE dir to OCS Inventory server plugins directories(see it in server config) and restart Apache.
In my case (CentOS 7):
```
/etc/ocsinventory-server/plugins/officepack.conf
/etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/Officepack/Map.pm
```

**Comment by skycrash** [comment]
Same problem here, anybody know if plugin work yet?
