### ISSUE TITLE
Installing the plugin gives error

### ISSUE THREAD

**Issue by vitotsg** [PluginsOCSInventory-NG/officepack#27]
Hi,

when trying to install the plugin I receive the following error:

"MySQL error: Installation aborted !"

**Comment by aslo611** [comment]
Hi, could you solve the problem? thanks

**Comment by Serizao** [comment]
[officepack.zip](https://github.com/PluginsOCSInventory-NG/officepack/files/1309943/officepack.zip)
i have repack  the plugin you can download it here the sql key was too big. I have propose correction

https://github.com/wleberre/officepack/blob/master/sql/officepack-guid-fr.sql
