### ISSUE TITLE
i can't see the licences

### ISSUE THREAD

**Issue by carlinchisart** [PluginsOCSInventory-NG/officepack#3]
Hi all,

Im sorry but i try to found a solution but is not posible, i installed the plugins, and i can see in Mysql DB and log of agent the data is send to server.

![mysqloffice](https://cloud.githubusercontent.com/assets/2440097/14725695/3bc04d70-07e3-11e6-8d9a-ad45ad6bfc76.png)

but when i access to ocs inventory ad the software option that this pc, i have this

![resultadohtmloffice](https://cloud.githubusercontent.com/assets/2440097/14725753/75ff83ac-07e3-11e6-9ff4-4f43542beb68.png)

i don't know what i have bad.

sorry for my english i speak spanish.

Thanks

**Comment by gillesdubois** [comment]
Hi,

This functionnality is not implemented is the new office plugin.
You need to use the office page on the menu Plugins -> Office licences manager or on each computer in software tab.

Regards,
Gilles Dubois.

**Comment by carlinchisart** [comment]
Hi gillesdubois,

i'm sorry, but you said i can see this on each computer in software tab, the second image is one computer in the software tab, after the software table, i see the title 

GESTIONNAIRE DES LICENCES MICROSOFT OFFICE

{"draw":"\n","recordsTotal":0,"recordsFiltered":0,"data":0,"customized":true}

but no show data.

i can see in the plugins->Ofice Key Managent the licences, but i can't see what computer have what licence, i Don't know if in this option is normal, if is normal, no problem, my question is in the software tap option for a computer.

Thanks

**Comment by gillesdubois** [comment]
Hi,

This is not integrated atm on this plugin version but will be added to a newer version.

Thanks for reporting.
Regards, Gilles Dubois.

**Comment by carlinchisart** [comment]
Hil Gillesdubois,

No problem!! thanks for your help, and thanks for this plugin, gread work!!

Bye
