### ISSUE TITLE
Mistake in vbs code

### ISSUE THREAD

**Issue by EdwardJR-BR** [PluginsOCSInventory-NG/officepack#31]
Hi

I do not know if this is the appropriate place for this message, I did not find another place to do this.
In a quick review, I noticed that at line #39 where " _aOffID **(5.1)** ="16.0"_ " should be " _aOffID **(5,1)** ="16.0"_ ".
There is a dot where there should be a comma, probably causing a failure to interpret the value of the last key of the array.
I'm wrong?

Excuse me for my bad English.

Salut

Je ne sais pas si c'est l'endroit approprié pour ce message, je n'ai pas trouvé d'autre endroit pour le faire.
Dans une revue rapide, j'ai remarqué qu'à la ligne # 39 où " _aOffID **(5.1)** ="16.0"_ " devrait être " _aOffID **(5,1)** ="16.0"_ ".
Il y a un point où il devrait y avoir une virgule, causant probablement un échec pour interpréter la valeur de la dernière clé du tableau.
J'ai tort?

Excusez-moi pour mon pauvre Français.

**Comment by steph78630** [comment]
Hi @EdwardJR-BR,

indeed, well seen, you're right ! Thank you for your contribution (obrigado) !

I request the update now !

Best regards, Stéphane

**Comment by gillesdubois** [comment]
Hi,

Seem i'm a bit late :D 
Thx for your contribution.

Regards,
Gilles Dubois

**Comment by gillesdubois** [comment]
Resolved by : https://github.com/PluginsOCSInventory-NG/officepack/pull/32
