### ISSUE TITLE
Officepack "MySQL error: Installation aborted !"

### ISSUE THREAD

**Issue by enguerrandadeline** [PluginsOCSInventory-NG/officepack#34]
Bonjour, j'ai aussi voulu installé le plugin Officepack toujours erreur MySQL error: Installation aborted !
Avez vous une solution ? Je suis sur une debian 9 avec Apache2 et php7 avec un OCS 2.0.

Hello, I also wanted to install the Officepack plugin always error MySQL error: Installation aborted!
Do you have a solution ? I am on a debian 9 with Apache2 and php7 with an OCS 2.0.

I'm sorry for my english I'm french.

**Comment by ekip-94** [comment]
https://github.com/PluginsOCSInventory-NG/officepack/files/1309943/officepack.zip

**Comment by helicrenz** [comment]
hello @aze789 ,

I try to install it but im not getting any data. 

![image](https://user-images.githubusercontent.com/42835226/46143704-64ac7080-c28d-11e8-8e2a-f6003c214a8b.png)

Any idea?

Regards,

Romeo

**Comment by helicrenz** [comment]
hello @aze789,

Thanks for your help.

i manage to fix the issue thanks for your plugin. I just added https://github.com/gehasia/officepack/blob/Office-2013-support/agent/msofficekey.vbs on client pc 
C:\Program Files (x86)\OCS Inventory Agent\plugins.


Is there anyway to include this on ocs package automate the script? any suggestion?
