### ISSUE TITLE
Plugin Installation Error 

### ISSUE THREAD

**Issue by sushantsatyal** [PluginsOCSInventory-NG/officepack#49]
While installing Office plugin I got the error: 
ERROR: check if Map.pm and [pluginName].conf exist
 
Please help me how do I solve it?

**Comment by charleneauger** [comment]
Hi @sushantsatyal ,
This bug has been fixed on OCSInventory-reports, please install the nightly to solve this problem:
http://download.ocsinventory-ng.org/nightly/

Best regards,
Charlene Auger
