### ISSUE TITLE
Access denied on detail page of licence

### ISSUE THREAD

**Issue by nEx-Ux1** [PluginsOCSInventory-NG/officepack#50]
Hi,
The installation of the plugin is ok, on my agent too

But when I want see result, OCS told me "ACCESS DENIED" , same result with different version
/index.php?function=officepack&value=2016
/index.php?function=officepack&value=2013
/index.php?function=officepack&value=2007

If I clic on a computer, software, at the bottom I can the the licence detail of this computer

Thanks

**Comment by bajlek** [comment]
I have the same issue

**Comment by juizdredd** [comment]
Edit File - /usr/share/ocsinventory-reports/ocsreports/extensions/officepack/ms_officepack/ms_officepack.php
Line 75
in
      $tab_options['LIEN_LBL']['Number']="index.php?".PAG_INDEX."=officepack&value=";
for
      $tab_options['LIEN_LBL']['Number']="index.php?".PAG_INDEX."=ms_officepack&value=";

**Comment by bajlek** [comment]
> Edit File - /usr/share/ocsinventory-reports/ocsreports/extensions/officepack/ms_officepack/ms_officepack.php
> Line 75
> ...


That helped! Thanks!

**Comment by nEx-Ux1** [comment]
> 
> 
> Edit File - /usr/share/ocsinventory-reports/ocsreports/extensions/officepack/ms_officepack/ms_officepack.php
> Line 75
> in
> $tab_options['LIEN_LBL']['Number']="index.php?".PAG_INDEX."=officepack&value=";
> for
> $tab_options['LIEN_LBL']['Number']="index.php?".PAG_INDEX."=ms_officepack&value=";

THANKS ! You're a BOSS ! Its works like a charm

**Comment by ghost** [comment]
vimaqui só pra falar que me ajudou, funcionou corretamente essa informação, obrigado.
