### ISSUE TITLE
Problème remonté office dans ocs

### ISSUE THREAD

**Issue by raphael38120** [PluginsOCSInventory-NG/officepack#53]
Bonjour,

Je rencontre une difficulté pour installer le plugin office j'ai bien réussi à l’installer dans ocs et j'ai mis en place le vbs dans le dossier plugin de ocs mais aucune licence ne remonte automatiquement.
Avez-vous une solution ?

Merci d'avance.

![image](https://user-images.githubusercontent.com/49481842/55875754-2bd34980-5b96-11e9-9f5f-aae5f8ce1bdc.png)

![image](https://user-images.githubusercontent.com/49481842/55875793-40174680-5b96-11e9-8b44-f9349d381d99.png)

![image](https://user-images.githubusercontent.com/49481842/55875857-63da8c80-5b96-11e9-9321-b94a4079893b.png)

**Comment by ilogus** [comment]
Bonjour,
Vérifiez si dans les fichiers du serveur (/perl/) et (/plugins) des fichiers de réception se sont bien installer ?

Cordialement,

**Comment by Doane-ND** [comment]
Bonjour, 
Je suis interessé par votre sujet, je suis au même stade que vous. Avez-vous eu une solution ?
Bonne journée.

**Comment by ilogus** [comment]
> 
> 
> Bonjour,
> Je suis interessé par votre sujet, je suis au même stade que vous. Avez-vous eu une solution ?
> Bonne journée.

Sur le serveur, vous avez bien installé avec un bouton le plugin ?
Sur le client avez-vous le fichier .vbs dans le dossier plugins ?

**Comment by Doane-ND** [comment]
Bonjour, 

 

Oui, j’ai testé avec le plugin antivirus et cela fonctionne et j’ai bien le fichier output.txt sur le pc

 

De : IloGus [mailto:notifications@github.com] 
Envoyé : jeudi 12 septembre 2019 15:17
À : PluginsOCSInventory-NG/officepack
Cc : Doane-ND; Comment
Objet : Re: [PluginsOCSInventory-NG/officepack] Problème remonté office dans ocs (#53)

 

Bonjour,
Je suis interessé par votre sujet, je suis au même stade que vous. Avez-vous eu une solution ?
Bonne journée.

Sur le serveur, vous avez bien installé avec un bouton le plugin ?
Sur le client avez-vous le fichier .vbs dans le dossier plugins ?

**Comment by ilogus** [comment]
> 
> Bonjour, Oui, j’ai testé avec le plugin antivirus et cela fonctionne et j’ai bien le fichier output.txt sur le pc 

Sur le serveur OCS inventory, les fichiers(dans /perl et /plugins) se sont bien installés ?

**Comment by Doane-ND** [comment]
Oui également.

 

De : IloGus [mailto:notifications@github.com] 
Envoyé : jeudi 12 septembre 2019 15:58
À : PluginsOCSInventory-NG/officepack
Cc : Doane-ND; Comment
Objet : Re: [PluginsOCSInventory-NG/officepack] Problème remonté office dans ocs (#53)

 

Bonjour, Oui, j’ai testé avec le plugin antivirus et cela fonctionne et j’ai bien le fichier output.txt sur le pc

Sur le serveur OCS inventory, les fichiers(dans /perl et /plugins) se sont bien installés ?

**Comment by ilogus** [comment]
> Oui également.

La seule solution que je peux vous apporter, c'est la copie des fichiers dans le dossier extensions vers le serveur de recepions des données :

`cd /etc/ocsinventory-server/`
`mv /usr/share/ocsinventory-reports/ocsreports/extensions/officepack/APACHE/officepack.conf plugins/`
`mkdir perl/Apache/Ocsinventory/Plugins/Officepack`
`cd perl/Apache/Ocsinventory/Plugins/Officepack/`
`mv /usr/share/ocsinventory-reports/ocsreports/extensions/officepack/APACHE/Map.pm .`

**Comment by Doane-ND** [comment]
Merci pour votre réponse 

 

Excusez moi pour le temps de réponse.

 

J’ai lancé les commandes et à priori ce n’est pas mieux.

 

De : IloGus [mailto:notifications@github.com] 
Envoyé : jeudi 12 septembre 2019 16:25
À : PluginsOCSInventory-NG/officepack
Cc : Doane-ND; Comment
Objet : Re: [PluginsOCSInventory-NG/officepack] Problème remonté office dans ocs (#53)

 

Oui également.

La seule solution que je peux vous apportez c'est la copie des fichiers dans le dossier extensions vers le serveurs de recepions des données :

cd /etc/ocsinventory-server/ mv /usr/share/ocsinventory-reports/ocsreports/extensions/officepack/APACHE/officepack.conf plugins/ mkdir perl/Apache/Ocsinventory/Plugins/Officepack cd perl/Apache/Ocsinventory/Plugins/Officepack/ mv /usr/share/ocsinventory-reports/ocsreports/extensions/officepack/APACHE/Map.pm .

**Comment by Doane-ND** [comment]
Une petite question, il y a-t-il un port à ouvrir sur les machines afin que ce plugin fonctionne correctement ?

 

De : IloGus [mailto:notifications@github.com] 
Envoyé : jeudi 12 septembre 2019 16:25
À : PluginsOCSInventory-NG/officepack
Cc : Doane-ND; Comment
Objet : Re: [PluginsOCSInventory-NG/officepack] Problème remonté office dans ocs (#53)

 

Oui également.

La seule solution que je peux vous apportez c'est la copie des fichiers dans le dossier extensions vers le serveurs de recepions des données :

cd /etc/ocsinventory-server/ mv /usr/share/ocsinventory-reports/ocsreports/extensions/officepack/APACHE/officepack.conf plugins/ mkdir perl/Apache/Ocsinventory/Plugins/Officepack cd perl/Apache/Ocsinventory/Plugins/Officepack/ mv /usr/share/ocsinventory-reports/ocsreports/extensions/officepack/APACHE/Map.pm .

**Comment by charleneauger** [comment]
Bonjour,

Voici le lien vers la documentation pour l'installation des extensions : [Using extension engine](http://wiki.ocsinventory-ng.org/10.Plugin-engine/Using-plugins-installer/). 

@Doane-ND, aucun port n'est à ouvrir pour que le plugin fonctionne.

Cordialement,
Charlene Auger
