### ISSUE TITLE
ERROR *** AGENT => Failed to send Inventory <HTTP Status Code #500>

### ISSUE THREAD

**Issue by ebenjbar** [PluginsOCSInventory-NG/officepack#55]
My configuration is OCS Server v2.6 and OfficePack v3. When I install officepack my clients can't send their inventories. Looking for the problem I have found the issue.

The offipack installation package doesn't create 2 filelds in 'officepack' table. The fields are:

- INSTALL
- GUID

I have created them and plugin works correctly.

I hope I can help some other people with my find.

**Comment by ajavor** [comment]
You're right. Missing entry at the end of the file (in the old version of the plugin is present):
/usr/share/ocsinventory-reports/ocsreports/extensions/officepack/sql/officepack.php

// Alter data table
$ object -> sql_query ("
ALTER TABLE `officepack` ADD COLUMN` GUID` varchar (255) DEFAULT NULL AFTER `OFFICEKEY`;
ALTER TABLE `officepack` ADD COLUMN` INSTALL` int (11) DEFAULT NULL AFTER `GUID`; ");

**Comment by fbomj** [comment]
Problem fixed. New release has been published.
