### ISSUE TITLE
Office 2016

### ISSUE THREAD

**Issue by ghost** [PluginsOCSInventory-NG/officepack#6]
The version of Office 2016 is counted as Office 2013.

you can fix the problem?

Thank you

**Comment by gillesdubois** [comment]
Hi,

Could you try to use this vbs ? https://github.com/boiss007/officepack/blob/master/agent/msofficekey.vbs
This one has been improved by @boiss007 to be compliant with office 2016

Regards,
Gilles Dubois.

**Comment by ghost** [comment]
I tried, but it does not work. The license is always displayed in 2013 instead of 2016

Edit: If i try to install boiss007 officepack I get this error: ```
ERROR: officepack is an invalid plugin, check your sources.

Installation aborted !

```
```

**Comment by ghost** [comment]
Installed your version:

WARNING **\* EXECUTABLE PLUGIN => Plugin <C:\Program Files (x86)\OCS Inventory Agent\plugins\msofficekey.vbs> does not produce any output
    EXECUTABLE PLUGIN => Searching for executable(s) in folder <C:\Program Files (x86)\OCS Inventory Agent\plugins>

**Comment by tsmr** [comment]
And with this ?
https://github.com/tsmr/officepack/blob/master/agent/msofficekey.vbs

**Comment by JackTor** [comment]
not, The same mistake. Not working.

**Comment by gillesdubois** [comment]
New version actually retrieve the office licenses : 
https://github.com/PluginsOCSInventory-NG/officepack/releases/download/1.1/officepack.zip
