### ISSUE TITLE
Can't install officekey plugin (2.6 server)

### ISSUE THREAD

**Issue by pintyoke** [PluginsOCSInventory-NG/officepack#63]
Hi

The script has successfully installed the plugin. However, nothing happens on the GUI during installation. Entries are partially created in the database. There is nothing in the logs!

I ran office-guide-fr manually and typed a few things so it already works. What causes this during installation? Could it be improved?

Thanks

**Comment by charleneauger** [comment]
Hi @pintyoke ,

Installation's bug has been fixed. You can install the new release.

Best regards,
Charlene Auger

**Comment by pintyoke** [comment]
Thank you very much!
