### ISSUE TITLE
Issue on installing on 2.7?

### ISSUE THREAD

**Issue by killmasta93** [PluginsOCSInventory-NG/officepack#64]
Hi,
Currently running 2.7, on the webgui it says correctly installed that i need to log out, as soon i log out and go back in i check the extension manager and still shows the office pack to install. See pictures
Thank you

![image](https://user-images.githubusercontent.com/13953629/83845236-13918880-a6ce-11ea-9504-8b4e7532d9c6.png)

![image](https://user-images.githubusercontent.com/13953629/83845248-1d1af080-a6ce-11ea-8bf1-53e080331d7e.png)

**Comment by TouTUN** [comment]
Hi, 
I've got exactly the same issue, it try to install the 3.1 version of the plugin and it's ok. I think there is a problem with the 3.1.1 version.

Moreover, in the 3.1.1 version, i have issue with the mysql script, which cause error. There is some "DEFAULT NULL" value on primary key and my sever reject it

**Comment by killmasta93** [comment]
thanks for the reply, could you pass me the version 3.1?
Thank you

**Comment by TouTUN** [comment]
https://github.com/PluginsOCSInventory-NG/officepack/releases

**Comment by killmasta93** [comment]
thanks installed it, quick question after installing the plugin is there another i need to take? because i dont see the keys coming in from the computers

**Comment by TouTUN** [comment]
Did you install the vbs script on the client ?

**Comment by killmasta93** [comment]
umm thats what im wondering where can i get the vbs script?

**Comment by killmasta93** [comment]
just found the scrip inside of the link you gave me above but not sure where to put the script? or do i just run it?

**Comment by MarcoTorres92** [comment]
Hi, the script you must put in the following path of your agents C: \ Program Files \ OCS Inventory Agent \ Plugins (version 2.7 agent) or C: \ Program Files (x86) \ OCS Inventory Agent \ Plugins (previous versions of agent) and then run ocsinventory.

Regards!

**Comment by killmasta93** [comment]
thanks for the reply, so i put the script inside and right click on the ocs inventory to re run but still shows blank on the OCS inventory web

![image](https://user-images.githubusercontent.com/13953629/84829740-d9898600-afed-11ea-84c3-528941fa3049.png)

![image](https://user-images.githubusercontent.com/13953629/84829912-28cfb680-afee-11ea-8d0f-7c1513c0d902.png)

![image](https://user-images.githubusercontent.com/13953629/84829982-456bee80-afee-11ea-9484-09dbca3f5c84.png)

**Comment by MarcoTorres92** [comment]
Did you try to install agent version 2.7? The teamviewer plugin works for me, the office plugin has not tried it yet

**Comment by MarcoTorres92** [comment]
Before I forget, I tell you that you also have a series of steps with python in the terminal since there it tells you how to use the new installation of extensions only applies to 2.6 and 2.7 servers at the moment, I share the page where you can  see this manual in case it is useful https://wiki.ocsinventory-ng.org/10.Plugin-engine/Using-plugins-installer/

**Comment by killmasta93** [comment]
Thanks for the reply, so i updated the agent the latest i found was 2.6 but still does not show any lics office keys

![image](https://user-images.githubusercontent.com/13953629/84855399-a7961500-b029-11ea-8a20-e3348a02a284.png)
as for the server part, do i need to run the commands? even if i got the extension imported?

So if i understood correctly

```
sudo apt install python3-pip
sudo pip3 install scp
```
then unzip the module and install though the web which i did then activate it

but im lost on the scripted communication server installation

**Comment by killmasta93** [comment]
edit: so i ran the following
and installed the packages
```

root@osc:/usr/share/ocsinventory-reports/ocsreports/tools# sudo python3 install_plugin.py
sudo: unable to resolve host osc
Where is the plugins location [/usr/share/ocsinventory-reports/ocsreports/extensions/]

[0] => officepack
0
The server is installed on the same server ? [y]/n

Where is the server location [/etc/ocsinventory-server]

officepackhas been successfully installed ! Don't forget to restart your Apache server
root@osc:/usr/share/ocsinventory-reports/ocsreports/tools# service ap
apache2              apache-htcacheclean  apparmor             apport               apt-daily            apt-daily-upgrade    
root@osc:/usr/share/ocsinventory-reports/ocsreports/tools# service ap
apache2              apache-htcacheclean  apparmor             apport               apt-daily            apt-daily-upgrade    
root@osc:/usr/share/ocsinventory-reports/ocsreports/tools# service apache2 restart
root@osc:/usr/share/ocsinventory-reports/ocsreports/tools# 
```

but checked again and nothing

**Comment by killmasta93** [comment]
@gillesdubois  quick question so did this problem get fixed?
