### ISSUE TITLE
Problem with the officepack 3.1.1

### ISSUE THREAD

**Issue by MarcoTorres92** [PluginsOCSInventory-NG/officepack#65]
In version 3.1 of the office pack, I read that there is an access denied problem supposedly fixed in 3.1.1 but I cannot install that new version because even if I log out and log in again, it still does not appear, can someone help me with that problem?

**Comment by TouTUN** [comment]
HI, i've got the same issue, the only way i found to install th eplugin is to use the previous release.
In the 3.1.1, it's look like there is some issue with the sql script

**Comment by MarcoTorres92** [comment]
Hi, then the version you installed is 3.1 or 3.0, since in 3.1 it gives an access denied error when entering the office key management

**Comment by TouTUN** [comment]
3.1, i don't have any acces deny when accessing the Office Key Management.
It's not a fresh install but an update of OCS

**Comment by charleneauger** [comment]
Hi @TouTUN @MarcoTorres92 ,

The installation bug has been fixed. You can install the new release :)

Best regards,
Charlene Auger
