### ISSUE TITLE
 problem with officepack 3.2 plugin

### ISSUE THREAD

**Issue by MarcoTorres92** [PluginsOCSInventory-NG/officepack#67]
Hello, sorry for the inconvenience, first of all, the recent plugin if it works when installed on my server, but from my agents, the plugin marks that no result is produced, by double clicking on the script if I get the info, I don't know if the plugin works with office 2016 home and business or is general.
![image](https://user-images.githubusercontent.com/66989169/84968126-63634d00-b0db-11ea-8cab-da64d36a02fb.png)
![image](https://user-images.githubusercontent.com/66989169/84968226-9e658080-b0db-11ea-8cb0-731c30ead603.png)

I need help since it is the last thing to put the server into production.

**Comment by MarcoTorres92** [comment]
I forgot to add the capture of the executed script and obtaining the information
![image](https://user-images.githubusercontent.com/66989169/84968420-0fa53380-b0dc-11ea-9361-250526c7055d.png)

**Comment by killmasta93** [comment]
same issue i run the vbs script i get the KEY but nothing shows up @MarcoTorres92 how to get the output of the log of the vbs script?

**Comment by gillesdubois** [comment]
Hi,

Thanks for you feedback.
On the first sight I think its related to an encoding / special character problem.
I will try to check that this week :)

Regards,
Gilles Dubois.

**Comment by charleneauger** [comment]
Hi,

A new release is available for officapack extension. Can you try and open a new issue if the problem persist ?

Best regards,
Charlene Auger

**Comment by killmasta93** [comment]
Thank you the new update is working
