### ISSUE TITLE
officepack v.3.4 - number of devices by license not visible

### ISSUE THREAD

**Issue by ajavor** [PluginsOCSInventory-NG/officepack#74]
I can't see a number of devices by licence. Where is it now?

![obraz](https://user-images.githubusercontent.com/32665748/185107025-003d8c57-a269-4d56-88de-5c727f471ade.png)

**Comment by gillesdubois** [comment]
Hi,

You have to check your profile.

You have to navigate to Config > Users > Profiles (click on the profile you user) > Check ms_officepack > Validate > Logout > Login again :)

We recently fixed an issue granting permissions automatically on some profile on install.

Regards,
Gilles.

**Comment by ajavor** [comment]
thanks,
I thought superadmin had all permissions on by default. It actually helped.
