### ISSUE TITLE
New plugin 3.5 problem

### ISSUE THREAD

**Issue by ajavor** [PluginsOCSInventory-NG/officepack#79]
After installing the new version of plugin 3.5, the "PRODUCTID", "GUID", "INSTALL", "NOTE" columns are not created in ocsreports (the columns are created correctly in the database).

![ocs_reports](https://github.com/PluginsOCSInventory-NG/officepack/assets/32665748/581fd08f-f958-4672-b59d-bd003f916d3a)

The agent script retrieves this data:
![agent_script](https://github.com/PluginsOCSInventory-NG/officepack/assets/32665748/6fba0f99-3e60-4392-8c85-4357f851177d)

**Comment by beegospl** [comment]
Same here, doesn't work.
