### ISSUE TITLE
Office license is not shown on the computer screen query

### ISSUE THREAD

**Issue by evaldoprestes** [PluginsOCSInventory-NG/officepack#8]
Plugin oficepack successfully installed, but when viewing computer data (hardware, software, devices, etc ...) could not find the office of the license information. Generating the XML file with the data from the computer, the office of the license information is there.

**Comment by evaldoprestes** [comment]
For details, check http://ask.ocsinventory-ng.org//4289/officepack-in-ocs-server-2-2-problem-and-solution

**Comment by ronator** [comment]
I did not have to do execute any of these steps mentioned above but restarting apache, of course. All permissions and files were in place. So can we consider this as done?

Btw, if you use https://github.com/boiss007/officepack/blob/master/agent/msofficekey.vbs on the agent, then you might run into a different issue: when you have two installations on one host (like Visio 2010 AND Office 2013) then this script will only detect one key (Visio in my case) and then quit. never reporting the other keys. I am not a vbs pro but I guess I should report this to @boiss007.
