### ISSUE TITLE
Windows 8.1/10

### ISSUE THREAD

**Issue by ghost** [PluginsOCSInventory-NG/officepack#9]
WARNING **\* EXECUTABLE PLUGIN => Executable plugin <C:\Program Files (x86)\OCS Inventory Agent\plugins\msofficekey.vbs> output is not UTF-8 encoded or an XML document, trying to UTF-8 encode

**Comment by vdeville** [comment]
Hey @Silente, 
Thank for your feedback, I'll watch it
Regards,

**Comment by ghost** [comment]
Any update?

**Comment by vdeville** [comment]
Hello @Silente 
For moment no update
Stay tund for future update
Regards

**Comment by gillesdubois** [comment]
@Silente 
Can you try with the new version plz ? 
https://github.com/PluginsOCSInventory-NG/officepack/releases/download/1.1/officepack.zip
